name: book_buddy
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  # ============================================================================
  # Use with the CupertinoIcons class for iOS style icons.
  # ============================================================================
  cupertino_icons: ^1.0.8
  
  # ============================================================================
  # Network
  # ============================================================================
  dio: ^5.9.2
  connectivity_plus: ^7.1.0

  # ============================================================================
  # State Management
  # ============================================================================
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # ============================================================================
  # Storage, Caching
  # ============================================================================
  hive_ce: ^2.19.3
  cached_network_image: ^3.4.1

  # ============================================================================
  # Navigation
  # ============================================================================
  go_router: ^17.2.3

  # ============================================================================
  # Utils
  # ============================================================================
  
  # ============================================================================
  # 
  # ============================================================================
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  # ============================================================================
  # Code Generation
  # ============================================================================
  build_runner: ^2.15.0
  riverpod_generator: ^4.0.3

  # ============================================================================
  # Linters
  # ============================================================================
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
